webrtc:
  key: 7a1c82ee-335c-4fd1-81d7-1c3323f9e40e   #Your SkyWay API key
  config: #未使用
    iceServers: #未使用
      - url: stun:stun.skyway.io:3478
      - url: turn:homeo@turn.bistri.com:80
        credential: homeo
app: #未使用
dice: #未使用